name: tanukiwi

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0+2
  path: ^1.8.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_riverpod: ^2.1.1
  kana_kit: ^2.0.0
  go_router: ^5.1.6
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Black.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Light.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Thin.otf
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Black.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Bold.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-ExtraLight.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Light.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Medium.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-Regular.otf
        - asset: assets/fonts/Noto_Serif_JP/NotoSerifJP-SemiBold.otf